services:
  reminder-bot:
    container_name: remindrix
    image: ghcr.io/outarde/remindrix:latest
    # All supported env variables are in /docker/example.env
    # It is more convenient to configure variables in .env file in the container folder
    # environment:
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "find /tmp/healthy -mmin -1 | grep -q . || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    # Uncomment it to run command when the bot starts
    # Typically, the <recover> command is used with the recovery key specified in the .env file to verify the device
    # See Readme or --help page for all supported commands
    # command: ["recover"]
