services:
  reminder-bot:
    container_name: remindrix
    image: ghcr.io/outarde/remindrix:latest
    # All supported env variables are in /docker/example.env
    # It is more convenient to configure variables in .env file in the container folder
    # environment:
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    # Uncomment it to run command when the bot starts
    # Typically, the <recover> command is used with the recovery key specified in the .env file to verify the device
    # See Readme or --help page for all supported commands
    # command: ["recover"]
